# Global Error Config
proxy_intercept_errors on;
#error_page 400 401 402 403 404 405 500 502 503 504 = @fallback;
error_page 400 401 403 404 405 500 502 503 504 /error-pages;

#location @fallback {
location = /error-pages {
    set $upstream_errors error-pages;
    resolver 127.0.0.11 valid=30s;
    proxy_pass http://$upstream_errors:8080;
    proxy_set_header X-Code $status;
    proxy_set_header X-Original-URI $request_uri;
    proxy_intercept_errors off;
    #rewrite ^(.*)$ / break;
    #rewrite ^ /?code=$status break;
    internal;
}
