# name: letsencrypt-webroot
# description: Fournie un emplacement pour le challenge HTTP LE - A inclure dans chaque virtualhost si LE en HTTP Challenge
# emplacement: server
# require:
# required_for: Let's Encrypt HTTP Challenge
# version: 1.0.0

location /.well-known/acme-challenge/ {
    root /var/www/letsencrypt;
}