#access_log /var/log/nginx/${host}.access.log;
#access_log /var/log/nginx/${host}.access.log combined if=$is_not_static;

# Added support for nginx after version 1.29.X: variable is no longer supported in paths
access_log /var/log/nginx/vhosts_access.log combined_vhost if=$is_not_static;

# If you want separate log files per virtual host, you must declare the directory and path in the virtual host file.