# name: remove-header
# description: supprimer des headers qui rertourne des informations sur le backend (upstream)
# emplacement: server
# require:
# version: 1.0.0

more_clear_headers Server;
more_clear_headers X-Powered-By;
more_clear_headers server;