# name: ssl-exemplecom
# description: exemple de configuration utilisant un certificat dans le dossier ssl - inclus egalement http2 - attention le genetateur de configuration ajouter automatiquement http2
# emplacement: server
# require:
# version: 1.0.0

http2 on;
ssl_certificate /ssl/exemplecom.cer;
ssl_certificate_key /ssl/exemplecom.key;