output {
  if [@metadata][pipeline] {
    elasticsearch {
      hosts => ["IP_ELK_SERVER:9200"]
      manage_template => false
      ssl => true
      ssl_certificate_verification => false
      index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
      pipeline => "%{[@metadata][pipeline]}"
      user => "elastic"
		  password => "changeme_please"
    }
  } else {
    elasticsearch {
      hosts => ["IP_ELK_SERVER:9200"]
      ssl => true
      ssl_certificate_verification => false
      manage_template => false
      index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
      user => "elastic"
		  password => "changeme_please"
    }
  }
}
