server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    location / {
        set $upstream_errors_ds error-pages;
        resolver 127.0.0.11 valid=30s;
        proxy_pass http://$upstream_errors_ds:8080;
    }
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;
    include snippets/ssl-exemplecom.conf;
}