# Bot definitions
# Only the following crawlers are allowed.

map $http_user_agent $is_good_bot {
        default 0;

        # Google & Bing
        "~*googlebot" 1;
        "~*bingbot" 1;
        "~*adidxbot" 1;
        
        # Other search bots
        "~*duckduckbot" 1;
        "~*qwantify" 1;
        "~*baiduspider" 1;
        "~*yandexbot" 1;
        "~*yeti" 1;
        
        # Social Networks
        "~*facebookexternalhit" 1;
        "~*twitterbot" 1;
        "~*pinterestbot" 1;
}
