# name: good-bots
# description: liste de bots (user agent) autorises (Moteur de rechercher et RS)
# require:
# usage: utiliser avec allow-visit-xxx - permet de bloquer les visites par rapport à un pays en laissant les bots visiter le site
# version: 1.0.0

map $http_user_agent $is_good_bot {
        default 0;

        # Google & Bing
        "~*googlebot" 1;
        "~*bingbot" 1;
        "~*adidxbot" 1;
        
        # Other search bots
        "~*duckduckbot" 1;
        "~*qwantify" 1;
        "~*baiduspider" 1;
        "~*yandexbot" 1;
        "~*yeti" 1;
        
        # Social Networks
        "~*facebookexternalhit" 1;
        "~*twitterbot" 1;
        "~*pinterestbot" 1;
}
