# name: ia-bots
# description: liste de bots IA (user agent) bloqués
# require:
# usage: ajouter le snippet block-ia-bots.conf dans le virtualhost
# version: 1.0.0

map $http_user_agent $ai_bot {
    default 0;
    # IA
    "~*Applebot-Extended"       1;
    "~*GPTBot"                  1;
    "~*CCBot"                   1;
    "~*Cohere-ai"               1;
    "~*ChatGPT-User"            1;
    "~*OAI-SearchBot"           1;
    "~*ClaudeBot"               1;
    "~*Claude-web"              1;
    "~*Google-Extended"         1;
    "~*GoogleOther"             1;
    "~*ImagesiftBot"            1;
    "~*Meta-ExternalAgent"      1;
    "~*PerplexityBot"           1;
    "~*YouBot"                  1;
    "~*FacebookBot"             1;
}