server{
    server_name opencloud.domain.tld;
    listen 443 ssl;
    http2 on;

    ssl_certificate /ssl/domain.tld.pem;
    ssl_certificate_key /ssl/domain.tld.key;

    error_log /var/log/nginx/opencloud.domain.tld.error.log;
    access_log /var/log/nginx/opencloud.domain.tld.access.log;

    client_max_body_size 10M;

    # Disable buffering - essential for SSE
    proxy_buffering off;
    proxy_request_buffering off;

    # Extend timeouts for long connections
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    keepalive_requests 100000;
    keepalive_timeout 5m;
    http2_max_concurrent_streams 512;

    # Prevent nginx from trying other upstreams
    proxy_next_upstream off;

    # Augmenter la taille autorisee des headers
    large_client_header_buffers 4 32k;
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;

    set $backend http://127.0.0.1:9200;

    location / {
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server{
    server_name opencloud-wopi.domain.tld;
    listen 443 ssl;

    ssl_certificate /ssl/domain.tld.pem;
    ssl_certificate_key /ssl/domain.tld.key;

    error_log /var/log/nginx/opencloud-wopi.domain.tld.error.log;
    access_log /var/log/nginx/opencloud-wopi.domain.tld.access.log;

    client_header_buffer_size 64k;
    large_client_header_buffers 4 64k;

    set $backend http://127.0.0.1:9300;

    location / {
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server{
    server_name opencloud-collabora.domain.tld;
    listen 443 ssl;

    error_log /var/log/nginx/opencloud-collabora.domain.tld.error.log;
    access_log /var/log/nginx/opencloud-collabora.domain.tld.access.log;

    ssl_certificate /ssl/domain.tld.pem;
    ssl_certificate_key /ssl/domain.tld.key;

    # Disable security
    proxy_hide_header X-Frame-Options;
    proxy_hide_header Content-Security-Policy;

    # Fix error 414 large header
    client_header_buffer_size 128k;
    large_client_header_buffers 4 128k;

    proxy_buffering off;
    proxy_request_buffering off;

    # Important pour les gros documents
    client_max_body_size 0;


    set $backend http://127.0.0.1:9980;

    # static files
    location ^~ /browser {
      proxy_pass $backend;
      proxy_set_header Host $host;
    }

    # WOPI discovery URL
    location ^~ /hosting/discovery {
      proxy_pass $backend;
      proxy_set_header Host $host;
    }

    # Capabilities
   location ^~ /hosting/capabilities {
     proxy_pass $backend;
     proxy_set_header Host $host;
   }

   location ~ ^/cool/(.*)/ws$ {
     proxy_pass $backend;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection "Upgrade";
     proxy_set_header Host $host;
     proxy_set_header X-Forwarded-Proto $scheme;
     proxy_read_timeout 36000s;
   }

   # download, presentation and image upload
   location ~ ^/cool {
     proxy_pass $backend;
     proxy_set_header Host $host;
   }
}
