# name: logging-config
# description: configuration format log et filtrage
# require:
# usage: 
# version: 1.0.0

# permet de ne pas logger les fichiers statiques, pour utiliser ce filtre
# ajouter if=$is_not_static à la fin de la directive access_log
map $request_uri $is_not_static {
    # On cherche les extensions ou patterns a ignorer
    #~*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf|map)$ 0;
    ~*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|otf|map)(\?|$) 0;
    ~*\/robots\.txt 0;
    
    # Par defaut, on logue
    default 1;
}

# Added support for nginx after version 1.29.X: variable is no longer supported in paths
log_format combined_vhost '$server_name $remote_addr - $remote_user [$time_local] '
                             '"$request" $status $body_bytes_sent '
                             '"$http_referer" "$http_user_agent"';