output {
  if [@metadata][pipeline] {
    elasticsearch {
      hosts => ["es01:9200"]
      manage_template => false
      ssl => true
      ssl_certificate_verification => false
      index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
      pipeline => "%{[@metadata][pipeline]}"
      user => "elastic"
      password => "changeme_please"
      #ilm_enabled => true
      #ilm_pattern => "{now/d}-000001"

    }
  } else {
    elasticsearch {
      hosts => ["es01:9200"]
      ssl => true
      ssl_certificate_verification => false
      manage_template => false
      index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "changeme_please"
      #ilm_enabled => true
      #ilm_pattern => "{now/d}-000001"

    }
  }
}
