# name: bad-bots
# description: liste de bots (user agent) bloqués (Crawler SEO et Securite)
# require:
# usage: ajouter le snippet block-bad-bots.conf dans le virtualhost
# version: 1.0.0

map $http_user_agent $bad_bot {
    default 0;
    # Crawler
    "~*AhrefsBot"               1;
    "~*Amazonbot"               1;
    "~*Bytespider"              1;
    "~*DataForSeoBot"           1;   
    "~*DotBot"                  1;
    "~*MJ12bot"                 1;
    "~*PetalBot"                1;
    "~*Rogerbot"                1;
    "~*SemrushBot"              1;
    "~*Seomoz"                  1;
    "~*Sogou"                   1;
    "~*VelenPublicWebCrawler"   1;
    "~*YanBot"                  1;
    # Security
    "~*Shodan"                  1;
    "~*Censys"                  1;
    "~*Nmap"                    1;
    "~*ZmEu"                    1;
    "~*Masscan"                 1;
}