# name: block-bad-bots
# description: block les "mauvais" bots defini dans conf/bad-bots.conf
# emplacement: server,location
# require: conf/bad-bots.conf
# version: 1.0.0

if ($bad_bot) {
    return 444;
}